apiVersion: batch/v1
kind: Job
metadata:
        name: webscraper
spec:
        template:
                metadata:
                        labels:
                                app: webscraper
                spec:
                        containers:
                                - name: webscraper
                                  image: DOCKER_USER/DOCKER_APP:BUILD_NUMBER
                                  ports:
                                          - containerPort: 5000
                        restartPolicy: OnFailure
