apiVersion: apps/v1
kind: Deployment
metadata:
        name: chatbot
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: chatbot
        template:
                metadata:
                        labels:
                                app: chatbot
                spec:
                        containers:
                                - name: chatbot-rasa
                                  image: REGISTRY:443/DOCKER_CHATBOT:latest
                                  ports:
                                          - containerPort: 5005
                                - name: chatbot-actions
                                  image: REGISTRY:443/DOCKER_ACTIONS:latest
                                  ports:
                                          - containerPort: 5055
